Repository kamero-research-base/supervisor_dash, pull requests merged in 2025-08, with the labels that each got.

#6 Bugs ft supervisor
  app/api/add/department/route.ts
  app/api/add/student/route.ts
  app/api/auth/login/route.ts
  app/api/departments/route.ts
  app/api/students/route.ts
  app/components/toggles/addStudent.tsx
  app/notifications/page.tsx
  app/pages/navBar.tsx
  app/profile/page.tsx
  app/students/page.tsx
Labels: bug

#7 bugs: input-placeholders fixed
  app/components/toggles/addResearch.tsx
Labels: bug

#15 ft: Add group assignment
  app/api/assignments/create/route.ts
  app/api/assignments/download-marks/route.ts
  app/api/assignments/email-marks/route.ts
  app/api/assignments/grade/route.ts
  app/api/assignments/invite/route.ts
  app/api/assignments/view/route.ts
  app/api/groups/[id]/route.ts
  app/api/groups/route.ts
  app/api/students/route.ts
  app/api/utils/assignmentEmails.ts
  app/components/assignment/page.tsx
  app/components/toggles/addAssignment.tsx
  app/components/toggles/manageGroups.tsx
  app/components/toggles/viewAssignment.tsx
  package.json
  yarn.lock
Labels: work in progress

#20 ft: Clean dashboard
  app/api/assignments/submissions/recent/route.ts
  app/pages/App.tsx
Labels: ready for merge
